camunda:
  client:
    mode: simple
    tenant-ids:
    - <default>
    auth:
      username: demo
      password: demo
    zeebe:
      enabled: true
      base-url: http://localhost:8086
      gateway-url: http://localhost:26500
      prefer-rest-over-grpc: false
    operate:
      enabled: true
      base-url: http://localhost:8081
    tasklist:
      enabled: true
      base-url: http://localhost:8082
    optimize:
      enabled: false
    identity:
      enabled: false
